version: "3.9"
services:
  mongo:
    image: mongo:4.2.5
  app:
    build: .
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - "8080:8000"
    volumes:
      - /Users/zhongjian/Desktop/CSE312/HW3/Obejct_5:/root
